version: "3"   # 파일규격버전

services: 

  db:   # 서비스이름
    image: mysql
    ports:
      - 3306:3306   # 포트 설정  외부:내부
    environment:
      - MYSQL_ROOT_PASSWORD=1234qwer   # 패스워드설정
      - MYSQL_DATABASE=jspdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    command:
      - --character-set-server=utf8mb4      # 인코딩
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - d:/dev/docker/db/mysql-db01    # 마운트 설정